package br.com.zup.rickandmortyemsimcity

const val CHARACTER_KEY = "Personagem"
const val ERROR_VIEWSTATE_MSG = "Não foi possível carregar a lista de personagens!"
const val SINGLELIVEEVET_LOG_MSG = "Múltiplos observáveis registraods mas apenas um será notificado das mudanças."
const val URL_BASE_IMG = "https://rickandmortyapi.com/api/character/avatar/"
const val JPEG = ".jpeg"
const val EMPTY_LIST_MSG = "Sua lista de personagens está vazia!"
const val FAIL_LOAD_FAVORITE_LIST_MSG = "Não foi possível carregar sua lista de personagens favoritos."
const val FAIL_UPDATE_FAVORITE_LIST_MSG = "Não foi possível atualizar seus personagens favoritos."
const val FAIL_UPDATE_CHARACTER_MSG = "Não foi possível atualizar o personagem!"
const val FAIL_GET_FAVORITE_CHARACTERS = "Não foi possível carregar seus personagens favoritos"
const val ERROR_UNFAVORITE_CHARACTER = "Não foi possível desfavoritar o personagem."
const val USER_KEY = "user"
const val NAME_ERROR_MESSAGE = "Favor informar nome"
const val EMAIL_ERROR_MESSAGE = "Favor informar email"
const val PASSWORD_ERROR_MESSAGE = "Favor informar senha"
const val CREATE_USER_ERROR_MESSAGE = "Erro ao criar usuário!"
const val LOGIN_ERROR_MESSAGE = "Não foi possivel realizar o login!"
const val IMAGE_COFFEE_ERROR_MESSAGE = "Tivemos um problema ao carregar a imagem!"